# Generated by Django 2.1.3 on 2018-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='name',
            field=models.CharField(default='Kein Name vorhanden', max_length=250, unique=True),
        ),
    ]
