# Generated by Django 2.1.3 on 2018-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daten', '0003_auto_20181116_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='day',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='month',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='year',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
